Swagger
wolox-training/sr-java pull request #11
Opened 2021-03-16 14:53 UTC by sebas97-stack

## Summary
- Config swagger
- add swagger controller user
- add swagger model user
## Trello Card
https://trello.com/c/AiF1aOfV

2021-03-17 14:02 UTC, martinremis requested changes
There is no Swagger docs for book controller?

2021-03-17 14:02 UTC, martinremis commented on src/main/java/wolox/training/controller/UserController.java
> +            @ApiResponse(code = 500, message = "Internal Server Error")})
Extract those string to constants. I should be a different file, accessible by every controller

2021-03-17 17:32 UTC, AleFalcon requested changes

2021-03-17 17:32 UTC, AleFalcon commented on src/main/java/wolox/training/config/SwaggerConfig.java
> +                .title("Training API")
These constants could be taken to a file of constants, as if there is any change in the future, there is a single place to touch the constants

2021-03-17 17:32 UTC, AleFalcon commented on src/main/java/wolox/training/constants/MessageSwagger.java
> +    String SUCCESS_GET_USER = "Successfully retrieved user";
This constants could be "static final"

2021-03-18 19:08 UTC, AleFalcon approved these changes
Great Job

2021-03-18 20:14 UTC, merged