Spring boot security
wolox-training/sr-java pull request #13
Opened 2021-03-18 20:26 UTC by sebas97-stack

## Sumary
- config sprig security
- add method change password
- rule update for not update password
## Trello Card
https://trello.com/c/0lG7fiox

2021-03-23 14:03 UTC, AleFalcon reviewed
I think that it's ok, but wait for Tincho

2021-03-25 14:14 UTC, martinremis requested changes

2021-03-25 14:14 UTC, martinremis commented on src/main/java/wolox/training/controller/UserController.java
> +        User user = userRepository.findById(id).orElseThrow(UserNotFoundException::new);
Don't you request for the previous password to compare to?

2021-03-25 18:18 UTC, martinremis approved these changes

2021-03-26 13:35 UTC, AleFalcon approved these changes
It's Ok

2021-03-29 13:07 UTC, merged